apiVersion: v1
kind: Service
metadata:
  name: mario-service
  labels:
    app: mario
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-types: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: mario
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
