# Persistent Volume claim 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sts-mongo-pvc
spec:
  storageClassName: sts-aws-gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---

# Persistent Volume
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sts-aws-gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: us-east-1a


